name = "SatelliteToolboxAtmosphericModels"
uuid = "5718ef0a-a30f-426d-bcd9-4cf31dd12909"
license = "MIT"
desc = "Atmospheric models for the SatelliteToolbox.jl ecosystem."
authors = ["Ronan Arraes Jardim Chagas <ronisbr@gmail.com>"]
version = "0.1.3"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PolynomialRoots = "3a141323-8675-5d76-9d11-e1df1406c778"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SatelliteToolboxBase = "9e17983a-0463-41a7-9a16-1682db6d8b66"
SatelliteToolboxCelestialBodies = "b0edd99f-a7ca-4aa6-9a1e-a53e8f506046"
SatelliteToolboxLegendre = "7fa26607-a272-47b2-9aa2-a6c1d419d9d2"
SpaceIndices = "5a540a4e-639f-452a-b107-23ea09ed4d36"
StaticArraysCore = "1e83bf80-4336-4d27-bf5d-d5a4f845583c"

[weakdeps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Diffractor = "9f5e2b26-1114-432f-b630-d3fe2085c51c"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[extensions]
SatelliteToolboxAtmosphericModelsChainRulesExt = ["ChainRulesCore"]

[compat]
Accessors = "0.1"
AllocCheck = "0.2"
ChainRulesCore = "1.25"
Crayons = "4"
DelimitedFiles = "1.6"
DifferentiationInterface = "0.6"
Diffractor = "0.2"
Enzyme = "0.13"
FiniteDiff = "2.26"
ForwardDiff = "0.10"
JET = "0.9.12"
LinearAlgebra = "1.6"
Mooncake = "0.4.39"
PolyesterForwardDiff = "0.1"
PolynomialRoots = "1"
Printf = "1.6"
Reexport = "1"
SatelliteToolboxBase = "0.2, 0.3"
SatelliteToolboxCelestialBodies = "0.1"
SatelliteToolboxLegendre = "1"
SpaceIndices = "1.2"
StaticArraysCore = "1.4"
Test = "1.6"
Zygote = "0.6"
julia = "1.6"

[extras]
AllocCheck = "9b6a8646-10ed-4001-bbdc-1d2f46dfbb1a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
Diffractor = "9f5e2b26-1114-432f-b630-d3fe2085c51c"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Mooncake = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"
PolyesterForwardDiff = "98d1487c-24ca-40b6-b7ab-df2af84e126b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[targets]
test = ["Test", "AllocCheck", "DelimitedFiles", "DifferentiationInterface", "Diffractor", "Enzyme", "FiniteDiff", "ForwardDiff", "JET", "Mooncake", "PolyesterForwardDiff", "Zygote"]
