name = "SatelliteToolboxAtmosphericModels"
uuid = "5718ef0a-a30f-426d-bcd9-4cf31dd12909"
license = "MIT"
desc = "Atmospheric models for the SatelliteToolbox.jl ecosystem"
authors = ["Ronan Arraes Jardim Chagas <ronisbr@gmail.com>"]
version = "0.1.1"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
PolynomialRoots = "3a141323-8675-5d76-9d11-e1df1406c778"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SatelliteToolboxBase = "9e17983a-0463-41a7-9a16-1682db6d8b66"
SatelliteToolboxCelestialBodies = "b0edd99f-a7ca-4aa6-9a1e-a53e8f506046"
SatelliteToolboxLegendre = "7fa26607-a272-47b2-9aa2-a6c1d419d9d2"
SpaceIndices = "5a540a4e-639f-452a-b107-23ea09ed4d36"

[compat]
Accessors = "0.1"
Crayons = "4"
PolynomialRoots = "1"
Reexport = "1"
SatelliteToolboxBase = "0.2, 0.3"
SatelliteToolboxCelestialBodies = "0.1"
SatelliteToolboxLegendre = "1"
SpaceIndices = "1"
julia = "1.6"

[extras]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "DelimitedFiles"]
