## Description #############################################################################
#
# Tests related to the Jacchia 1977 model.
#
## Test Data ###############################################################################
#
# The files ja77_stat.dat and ja77_dynm.dat contain the reference outputs of the Fortran
# implementation of the Jacchia 1977 model [2], developed at the Instituto Nacional de
# Pesquisas Espaciais (INPE) by Bento Silva de Matos and Valdemir Carrara. They were
# obtained from the archive:
#
#     https://github.com/jacobwilliams/INPE-atmosphere-models
#
# at the commit bf01d45 (2019-12-14), directory `jac77f`. The files can be regenerated by
# compiling and running the test program `ja77_test.for` available in the same directory
# with the sources `ja77.for` and `atsu.for`:
#
#     ja77_stat.dat: static model (routine ISMADE) for F10 = F10ₐ = 100 sfu and altitudes
#         from 90 km to 2000 km in steps of 10 km.
#
#     ja77_dynm.dat: dynamic model (routine ISDAMO) for F10 = F10ₐ = 100 sfu, Kp = 5,
#         600 km, Sun at the origin of the inertial frame, Greenwich sidereal time of
#         293.49°, and modified Julian date (1950.0) 22476, sweeping the right ascension
#         from -180° to +180° and the latitude from -60° to +60°.
#
# The original code is distributed by INPE for free use provided that due credit is given
# to the authors, as stated in the LICENSE.txt file of the archive above.
#
## References ##############################################################################
#
# [1] Jacchia, L. G (1977). Thermospheric temperature, density and composition: New models.
#     SAO Special Report #375.
#
# [2] de Matos, B. S., Carrara, V (1985-1987). Fortran implementation of the Jacchia 1977
#     model. INPE, São José dos Campos, BR.
#
############################################################################################

# == Functions: jacchia1977 ================================================================

############################################################################################
#                                       Test Results                                       #
############################################################################################
#
# The static model is compared against the file ja77_stat.dat, which contains the output of
# the reference implementation [2] for F10 = F10ₐ = 100 sfu and altitudes from 90 km to
# 2000 km. The tolerances are the half-ULP of the fixed-width format used to generate the
# file.
#
############################################################################################

@testset "Static Model" begin
    T½ = 5.48 * 100.0^0.8 + 101.8 * 100.0^0.4

    count = 0

    for l in readlines("ja77_stat.dat")
        m = match(r"^\s+(\d+)\s", l)
        m === nothing && continue

        alt = parse(Int, m.captures[1])
        (90 <= alt <= 2000) || continue

        # The line format is (1X, I4, 1X, F6.2, F8.3, 2F7.2, 6F7.3).
        wmol    = parse(Float64, l[7:12])
        log₁₀_ρ = parse(Float64, l[13:20])
        T_exo   = parse(Float64, l[21:27])
        T_local = parse(Float64, l[28:34])
        an      = [parse(Float64, l[(35 + 7 * (i - 1)):(34 + 7 * i)]) for i in 1:6]

        log₁₀_n, M̄, ρ = AtmosphericModels._jacchia1977_static(T½, Float64(alt))

        Tz = AtmosphericModels._jacchia1977_temperature(
            Float64(alt), AtmosphericModels._jacchia1977_profile_params(T½)
        )

        @test M̄ ≈ wmol atol = 0.006
        @test log10(ρ) ≈ log₁₀_ρ atol = 0.0006
        @test T½ ≈ T_exo atol = 0.006
        @test Tz ≈ T_local atol = 0.006

        for i in 1:6
            @test log₁₀_n[i] ≈ an[i] atol = 0.0006
        end

        count += 1
    end

    # Make sure we compared all the altitudes in the file.
    @test count == 192
end

############################################################################################
#                                       Test Results                                       #
############################################################################################
#
# The dynamic model is compared against the file ja77_dynm.dat, which contains the output
# of the reference implementation [2] for:
#
#   F10  = 100 sfu
#   F10ₐ = 100 sfu
#   Kp   = 5
#   h    = 600 km
#
# with the Sun at the origin of the inertial frame (right ascension and declination equal
# to zero), Greenwich sidereal time of 293.49°, and modified Julian date (1950.0) 22476.
# The right ascension of the point varies from -180° to +180° and the latitude assumes the
# values -60°, -30°, 0°, +30°, and +60°. The tolerances are the half-ULP of the fixed-width
# format used to generate the file.
#
############################################################################################

@testset "Dynamic Model" begin
    F10  = 100.0
    F10ₐ = 100.0
    Kp   = 5.0
    z    = 600.0
    gst  = 293.49 / 180 * 3.141592
    Φ    = mod(22476 / 365.2422, 1)
    lats = deg2rad.([-60.0, -30.0, 0.0, 30.0, 60.0])
    Mi   = AtmosphericModels._JACCHIA1977_CONSTANTS.Mi

    count = 0

    for l in readlines("ja77_dynm.dat")
        m = match(r"^\s*(-?\d+)\s", l)
        m === nothing && continue
        occursin("mmolms", l) && continue

        ra_deg = parse(Int, m.captures[1])
        (-180 <= ra_deg <= 180) || continue

        # The line format is (1X, I4, 5(1X, F6.2, F8.3)).
        vals = [
            (
                parse(Float64, l[(7 + 15 * (i - 1)):(12 + 15 * (i - 1))]),
                parse(Float64, l[(13 + 15 * (i - 1)):(20 + 15 * (i - 1))]),
            ) for i in 1:5
        ]

        # The reference test program uses this truncated value of π.
        ra = ra_deg * 3.141592 / 180

        for (i, ϕ) in enumerate(lats)
            out = AtmosphericModels._jacchia1977_dynamic(
                z, ϕ, ra, 0.0, 0.0, ra - gst, Φ, F10, F10ₐ, Kp
            )

            n = (
                out.He_number_density,
                out.O2_number_density,
                out.N2_number_density,
                out.Ar_number_density,
                out.O_number_density,
                out.H_number_density,
            )

            M̄ = sum(n .* Mi) / sum(n)

            @test M̄ ≈ vals[i][1] atol = 0.006
            @test log10(out.total_density) ≈ vals[i][2] atol = 0.0006
        end

        count += 1
    end

    # Make sure we compared all the right ascensions in the file.
    @test count == 73
end

############################################################################################
#                                       Test Results                                       #
############################################################################################
#
# Section 9 of the report [1] contains a worked example: 1974-05-04 14:00 UT, 40° N, 45° W,
# 320 km, F10 = 114 sfu, F10ₐ = 87.6 sfu, and delayed Kp = 5.0, leading to T½ = 873.1 K and
# log₁₀ ρ = -10.934. Notice that the example in the report ignores eq. 32 and rounds every
# intermediate result. Hence, we use a loose tolerance for the density.
#
############################################################################################

@testset "SR-375 Worked Example" begin
    jd  = date_to_jd(1974, 5, 4, 14, 0, 0)
    out = AtmosphericModels.jacchia1977(jd, deg2rad(40), deg2rad(-45), 320e3, 114.0, 87.6, 5.0)

    @test out.exospheric_temperature ≈ 873.1 atol = 0.1
    @test log10(out.total_density) ≈ -10.934 atol = 0.05
end

############################################################################################
#                                       Test Results                                       #
############################################################################################
#
# We select a day and run the model with and without passing the space indices. The result
# must be the same. The space indices fetched for the instant 2023-01-01T10:00:00.000 at
# 23° S, 45° W are:
#
#   F10  = 178.3 sfu (lagged by 1.1821357920055 days)
#   F10ₐ = 155.76634372870583 sfu (Gaussian-weighted mean with 71-day standard width)
#   Kp   = 3.0 (delayed by 0.29100570997169495 days)
#
############################################################################################

@testset "Fetching All Space Indices" begin
    SpaceIndices.init()

    instant = DateTime("2023-01-01T10:00:00")
    ϕ_gd    = -23 |> deg2rad
    λ       = -45 |> deg2rad
    F10     = 178.3
    F10ₐ    = 155.76634372870583
    Kp      = 3.0

    for h in (150e3, 400e3, 1000e3)
        expected = AtmosphericModels.jacchia1977(instant, ϕ_gd, λ, h, F10, F10ₐ, Kp)
        result   = AtmosphericModels.jacchia1977(instant, ϕ_gd, λ, h)

        @test result.total_density ≈ expected.total_density
        @test result.temperature ≈ expected.temperature
        @test result.exospheric_temperature ≈ expected.exospheric_temperature
        @test result.N2_number_density ≈ expected.N2_number_density
        @test result.O2_number_density ≈ expected.O2_number_density
        @test result.O_number_density ≈ expected.O_number_density
        @test result.Ar_number_density ≈ expected.Ar_number_density
        @test result.He_number_density ≈ expected.He_number_density
        @test result.H_number_density ≈ expected.H_number_density
    end
end

@testset "Show" begin
    result = AtmosphericModels.jacchia1977(
        DateTime("2023-01-01T10:00:00"), 0, 0, 500e3, 100, 100, 3
    )

    str = sprint(show, result)
    @test startswith(str, "Jacchia 1977 output (ρ = ")

    str = sprint(show, MIME("text/plain"), result)
    @test startswith(str, "Jacchia 1977 Atmospheric Model Result:")
    @test occursin("Total density", str)
    @test occursin("H  number density", str)
end

@testset "Errors" begin
    @test_throws ArgumentError AtmosphericModels.jacchia1977(
        now(), 0, 0, 89.9e3, 100, 100, 3
    )
    @test_throws ArgumentError AtmosphericModels.jacchia1977(
        now(), 0, 0, 2000.1e3, 100, 100, 3
    )
end
