## Description #############################################################################
#
# Tests related to the Jacchia 1977 model.
#
## Test Data ###############################################################################
#
# The files ja77_stat.dat and ja77_dynm.dat contain the reference outputs of the Fortran
# implementation of the Jacchia 1977 model [2], developed at the Instituto Nacional de
# Pesquisas Espaciais (INPE) by Bento Silva de Matos and Valdemir Carrara. They were
# obtained from the archive:
#
#     https://github.com/jacobwilliams/INPE-atmosphere-models
#
# at the commit bf01d45 (2019-12-14), directory `jac77f`. The files can be regenerated by
# compiling and running the test program `ja77_test.for` available in the same directory
# with the sources `ja77.for` and `atsu.for`:
#
#     ja77_stat.dat: static model (routine ISMADE) for F10 = F10ₐ = 100 sfu and altitudes
#         from 90 km to 2000 km in steps of 10 km.
#
#     ja77_dynm.dat: dynamic model (routine ISDAMO) for F10 = F10ₐ = 100 sfu, Kp = 5,
#         600 km, Sun at the origin of the inertial frame, Greenwich sidereal time of
#         293.49°, and modified Julian date (1950.0) 22476, sweeping the right ascension
#         from -180° to +180° and the latitude from -60° to +60°.
#
# The original code is distributed by INPE for free use provided that due credit is given
# to the authors, as stated in the LICENSE.txt file of the archive above.
#
## References ##############################################################################
#
# [1] Jacchia, L. G (1977). Thermospheric temperature, density and composition: New models.
#     SAO Special Report #375.
#
# [2] de Matos, B. S., Carrara, V (1985-1987). Fortran implementation of the Jacchia 1977
#     model. INPE, São José dos Campos, BR.
#
############################################################################################

# == Functions: jacchia1977 ================================================================

############################################################################################
#                                       Test Results                                       #
############################################################################################
#
# The static model is compared against the file ja77_stat.dat, which contains the output of
# the reference implementation [2] for F10 = F10ₐ = 100 sfu and altitudes from 90 km to
# 2000 km. The tolerances are the half-ULP of the fixed-width format used to generate the
# file, except for the values affected by the hydrogen number density. Here, we depart from
# the reference implementation [2], which integrates the hydrogen over a window displaced
# by one Boole panel below 500 km and omits the total number density factor of the flux
# term of eq. 16 [1] above 500 km. The observed deviations from the file are at most
# 0.024 in the hydrogen log-density (at 150 km), 0.0010 in the total log-density (at
# 1990 km, where the hydrogen dominates the mass), and 0.0061 in the mean molecular mass
# (at 1590 km).
#
############################################################################################

@testset "Static Model" begin
    T½ = 5.48 * 100.0^0.8 + 101.8 * 100.0^0.4

    count = 0

    for l in readlines(joinpath(@__DIR__, "ja77_stat.dat"))
        m = match(r"^\s+(\d+)\s", l)
        m === nothing && continue

        alt = parse(Int, m.captures[1])
        (90 <= alt <= 2000) || continue

        # The line format is (1X, I4, 1X, F6.2, F8.3, 2F7.2, 6F7.3).
        wmol    = parse(Float64, l[7:12])
        log₁₀_ρ = parse(Float64, l[13:20])
        T_exo   = parse(Float64, l[21:27])
        T_local = parse(Float64, l[28:34])
        an      = [parse(Float64, l[(35 + 7 * (i - 1)):(34 + 7 * i)]) for i in 1:6]

        log₁₀_n, M̄, ρ = AtmosphericModels._jacchia1977_static(T½, Float64(alt))

        Tz = AtmosphericModels._jacchia1977_temperature(
            Float64(alt), AtmosphericModels._jacchia1977_profile_params(T½)
        )

        @test M̄ ≈ wmol atol = 0.008
        @test log10(ρ) ≈ log₁₀_ρ atol = 0.0015
        @test T½ ≈ T_exo atol = 0.006
        @test Tz ≈ T_local atol = 0.006

        # The reference implementation clamps negative base-10 logarithms to 0 before
        # printing, whereas we return the true values. Hence, we apply the same clamp
        # before comparing.
        for i in 1:5
            @test max(log₁₀_n[i], 0.0) ≈ an[i] atol = 0.0006
        end

        # See the explanation about the hydrogen tolerance in the comment above.
        @test max(log₁₀_n[6], 0.0) ≈ an[6] atol = 0.03

        count += 1
    end

    # Make sure we compared all the altitudes in the file.
    @test count == 192

    # The hydrogen number density must be continuous across the 500 km anchor, in which the
    # integration switches between the downward and upward branches.
    log₁₀_n_m, ~, ~ = AtmosphericModels._jacchia1977_static(T½, 499.9)
    log₁₀_n_0, ~, ~ = AtmosphericModels._jacchia1977_static(T½, 500.0)
    log₁₀_n_p, ~, ~ = AtmosphericModels._jacchia1977_static(T½, 500.1)

    @test log₁₀_n_m[6] ≈ log₁₀_n_0[6] atol = 1e-3
    @test log₁₀_n_p[6] ≈ log₁₀_n_0[6] atol = 1e-3

    # The number density of heavily depleted species must not be clamped to 1 / m³.
    log₁₀_n_top, ~, ~ = AtmosphericModels._jacchia1977_static(T½, 2000.0)
    @test log₁₀_n_top[4] < -10
end

############################################################################################
#                                       Test Results                                       #
############################################################################################
#
# The dynamic model is compared against the file ja77_dynm.dat, which contains the output
# of the reference implementation [2] for:
#
#   F10  = 100 sfu
#   F10ₐ = 100 sfu
#   Kp   = 5
#   h    = 600 km
#
# with the Sun at the origin of the inertial frame (right ascension and declination equal
# to zero), Greenwich sidereal time of 293.49°, and modified Julian date (1950.0) 22476.
# The right ascension of the point varies from -180° to +180° and the latitude assumes the
# values -60°, -30°, 0°, +30°, and +60°. The tolerances are the half-ULP of the fixed-width
# format used to generate the file.
#
############################################################################################

@testset "Dynamic Model" begin
    F10  = 100.0
    F10ₐ = 100.0
    Kp   = 5.0
    z    = 600.0
    gst  = 293.49 / 180 * 3.141592
    Φ    = mod(22476 / 365.2422, 1)
    lats = deg2rad.([-60.0, -30.0, 0.0, 30.0, 60.0])
    Mi   = AtmosphericModels._JACCHIA1977_CONSTANTS.Mi

    count = 0

    for l in readlines(joinpath(@__DIR__, "ja77_dynm.dat"))
        m = match(r"^\s*(-?\d+)\s", l)
        m === nothing && continue
        occursin("mmolms", l) && continue

        ra_deg = parse(Int, m.captures[1])
        (-180 <= ra_deg <= 180) || continue

        # The line format is (1X, I4, 5(1X, F6.2, F8.3)).
        vals = [
            (
                parse(Float64, l[(7 + 15 * (i - 1)):(12 + 15 * (i - 1))]),
                parse(Float64, l[(13 + 15 * (i - 1)):(20 + 15 * (i - 1))]),
            ) for i in 1:5
        ]

        # The reference test program uses this truncated value of π.
        ra = ra_deg * 3.141592 / 180

        for (i, ϕ) in enumerate(lats)
            out = AtmosphericModels._jacchia1977_dynamic(
                z, ϕ, ra, 0.0, 0.0, ra - gst, Φ, F10, F10ₐ, Kp
            )

            n = (
                out.He_number_density,
                out.O2_number_density,
                out.N2_number_density,
                out.Ar_number_density,
                out.O_number_density,
                out.H_number_density,
            )

            M̄ = sum(n .* Mi) / sum(n)

            @test M̄ ≈ vals[i][1] atol = 0.006
            @test log10(out.total_density) ≈ vals[i][2] atol = 0.0006
        end

        count += 1
    end

    # Make sure we compared all the right ascensions in the file.
    @test count == 73
end

############################################################################################
#                                       Test Results                                       #
############################################################################################
#
# Section 9 of the report [1] contains a worked example: 1974-05-04 14:00 UT, 40° N, 45° W,
# 320 km, F10 = 114 sfu, F10ₐ = 87.6 sfu, and delayed Kp = 5.0, leading to T½ = 873.1 K and
# log₁₀ ρ = -10.934.
#
# Our implementation reproduces every intermediate quantity of the example (Sun geometry,
# mean molecular mass, pseudo exospheric temperatures, static number densities, exospheric
# temperature variation, seasonal-latitudinal variation, and semiannual variation) to the
# precision printed in the report. However, two values of the example are inconsistent
# with the equations of the report itself:
#
#   1. The homopause displacement contributions ΔH log nᵢ of the example imply
#      Δz_H ≈ 7720 m, which corresponds to a coefficient of 7.5e3 in eq. 33 instead of the
#      printed 5.0e3 (which yields Δz_H ≈ 5147 m for ΔG T∞ = 122 K).
#
#   2. The equatorial wave contribution Δe log nᵢ = +0.063 of the example corresponds to
#      eq. 35 evaluated at the geographic latitude (40°), whereas the equation prescribes
#      the geomagnetic latitude (50.47°), which yields +0.029.
#
# We follow the equations as printed, like the reference implementation [2]. Consequently,
# the assembled example values (final log₁₀ nᵢ and log₁₀ ρ = -10.934) cannot be reproduced
# exactly: following the equations yields log₁₀ ρ = -10.898. Hence, we use a loose
# tolerance for the total density and tight tolerances for all the consistent intermediate
# quantities.
#
############################################################################################

@testset "SR-375 Worked Example" begin
    jd = date_to_jd(1974, 5, 4, 14, 0, 0)
    ϕ  = deg2rad(40)
    λ  = deg2rad(-45)

    out = AtmosphericModels.jacchia1977(jd, ϕ, λ, 320e3, 114.0, 87.6, 5.0)

    @test out.exospheric_temperature ≈ 873.1 atol = 0.1
    @test log10(out.total_density) ≈ -10.934 atol = 0.05

    # The local temperature must tend to the local exospheric temperature at high
    # altitudes. The report evaluates the quiet local exospheric temperature as
    # T₀(∞) = 939.3 K and the disturbed one as T₀(∞) + ΔG T∞ = 1061 K.
    out_disturbed = AtmosphericModels.jacchia1977(jd, ϕ, λ, 2000e3, 114.0, 87.6, 5.0)
    out_quiet     = AtmosphericModels.jacchia1977(jd, ϕ, λ, 2000e3, 114.0, 87.6, 0.0)

    @test out_disturbed.temperature ≈ 1061.0 atol = 0.5
    @test out_quiet.temperature ≈ 939.3 atol = 0.1

    # == Intermediate Quantities of the Example ============================================

    # Sun geometry.
    s_i = AtmosphericModels.sun_position_mod(jd)
    δs  = atan(s_i[3], √(s_i[1]^2 + s_i[2]^2))
    Ωs  = atan(s_i[2], s_i[1])
    Ωp  = λ + jd_to_gmst(jd)
    H   = rem2pi(Ωp - Ωs, RoundNearest)

    @test rad2deg(δs) ≈ +15.96 atol = 0.01
    @test rad2deg(H) ≈ -14.18 atol = 0.02

    # Mean molecular mass at 320 km for the mean exospheric temperature.
    T½ = out.exospheric_temperature
    ~, M̄, ~ = AtmosphericModels._jacchia1977_static(T½, 320.0)
    @test M̄ ≈ 16.90 atol = 0.01

    # Pseudo exospheric temperatures and number densities of the diurnal variation. The
    # example values in the internal order (He, O₂, N₂, Ar, O, H) are
    # Θᵢ = (996.8, 950.8, 952.6, 948.2, 963.9, 939.3) K and
    # log₁₀ (nᵢ)₀ = (12.719, 12.224, 13.670, 9.765, 14.587, 11.265).
    al, ~, Θ_H = AtmosphericModels._jacchia1977_diurnal(T½, Ωp, Ωs, δs, ϕ, 320.0, M̄)

    @test Θ_H ≈ 939.3 atol = 0.1

    example_log₁₀_n₀ = (12.719, 12.224, 13.670, 9.765, 14.587, 11.265)

    for i in 1:6
        @test al[i] ≈ example_log₁₀_n₀[i] atol = 0.005
    end

    # Geomagnetic variation of the exospheric temperature.
    ~, ΔT∞ = AtmosphericModels._jacchia1977_geomagnetic(Θ_H, 5.0, ϕ, λ, 320.0)
    @test ΔT∞ ≈ 122 atol = 0.5

    # Seasonal-latitudinal variation (He and O columns of the example).
    Φ   = mod((jd - 2433282.5) / 365.2422, 1)
    Δsl = AtmosphericModels._jacchia1977_seasonal_latitudinal(Φ, δs, ϕ, 320.0)

    @test Δsl[1] ≈ -0.346 atol = 0.001
    @test Δsl[5] ≈ -0.070 atol = 0.001

    # Semiannual variation.
    @test AtmosphericModels._jacchia1977_semiannual(Φ, 320.0) ≈ +0.037 atol = 0.001
end

############################################################################################
#                                       Test Results                                       #
############################################################################################
#
# We select a day and run the model with and without passing the space indices. The result
# must be the same. The space indices fetched for the instant 2023-01-01T10:00:00.000 at
# 23° S, 45° W, using the 10.7-cm flux adjusted to 1 AU as used to fit the Jacchia models,
# are:
#
#   F10  = 159.5 sfu (value of 2022-12-31, lagged by 1.1821357920055 days)
#   F10ₐ = 152.12946765567946 sfu (Gaussian-weighted mean with 71-day standard width)
#   Kp   = 3.0 (delayed by 0.29100570997169495 days)
#
############################################################################################

@testset "Fetching All Space Indices" begin
    SpaceIndices.init()

    instant = DateTime("2023-01-01T10:00:00")
    ϕ_gd    = -23 |> deg2rad
    λ       = -45 |> deg2rad
    F10     = 159.5
    F10ₐ    = 152.12946765567946
    Kp      = 3.0

    for h in (150e3, 400e3, 1000e3)
        expected = AtmosphericModels.jacchia1977(instant, ϕ_gd, λ, h, F10, F10ₐ, Kp)
        result   = AtmosphericModels.jacchia1977(instant, ϕ_gd, λ, h)

        @test result.total_density ≈ expected.total_density
        @test result.temperature ≈ expected.temperature
        @test result.exospheric_temperature ≈ expected.exospheric_temperature
        @test result.N2_number_density ≈ expected.N2_number_density
        @test result.O2_number_density ≈ expected.O2_number_density
        @test result.O_number_density ≈ expected.O_number_density
        @test result.Ar_number_density ≈ expected.Ar_number_density
        @test result.He_number_density ≈ expected.He_number_density
        @test result.H_number_density ≈ expected.H_number_density
    end

    # The automatic fetching must work for recent epochs, in which the Gaussian window of
    # the averaged F10.7 is truncated at the available data span.
    result = AtmosphericModels.jacchia1977(now(UTC), 0.0, 0.0, 500e3)
    @test isfinite(result.total_density)
end

############################################################################################
#                                       Test Results                                       #
############################################################################################
#
# The keyword `geomagnetic_profile` selects how the geomagnetic variation of the exospheric
# temperature is applied to the temperature profile used to compute the geomagnetic
# variation of the number densities. `Val(:constant)` (default) increases the entire
# profile, as in the reference implementation [2], whereas `Val(:tanh)` weights the
# increase by the altitude-dependent profile of eq. 32 of [1]. Hence, the default must
# match the reference behavior exactly, the two options must differ when Kp > 0, and they
# must match exactly when Kp = 0.
#
############################################################################################

@testset "Geomagnetic Profile Options" begin
    jd = date_to_jd(1974, 5, 4, 14, 0, 0)
    ϕ  = deg2rad(40)
    λ  = deg2rad(-45)

    for h in (150e3, 600e3)
        out_default  = AtmosphericModels.jacchia1977(jd, ϕ, λ, h, 114.0, 87.6, 5.0)
        out_constant = AtmosphericModels.jacchia1977(jd, ϕ, λ, h, 114.0, 87.6, 5.0; geomagnetic_profile = Val(:constant))
        out_tanh     = AtmosphericModels.jacchia1977(jd, ϕ, λ, h, 114.0, 87.6, 5.0; geomagnetic_profile = Val(:tanh))

        @test out_constant.total_density == out_default.total_density
        @test out_tanh.total_density != out_constant.total_density
        @test isfinite(out_tanh.total_density)
    end

    # Both options must match exactly when there is no geomagnetic activity.
    out_constant = AtmosphericModels.jacchia1977(
        jd, ϕ, λ, 300e3, 114.0, 87.6, 0.0; geomagnetic_profile = Val(:constant)
    )
    out_tanh = AtmosphericModels.jacchia1977(
        jd, ϕ, λ, 300e3, 114.0, 87.6, 0.0; geomagnetic_profile = Val(:tanh)
    )

    @test out_tanh.total_density == out_constant.total_density

    # Invalid options must throw.
    @test_throws ArgumentError AtmosphericModels.jacchia1977(
        jd, ϕ, λ, 300e3, 114.0, 87.6, 5.0; geomagnetic_profile = Val(:linear)
    )
end

############################################################################################
#                                       Test Results                                       #
############################################################################################
#
# The STELA variant is compared against the Java implementation of the Jacchia 1977 model
# used by the CNES tools STELA and PATRIUS (class
# fr.cnes.sirius.patrius.stela.forces.atmospheres.Jacchia77, PATRIUS 4.16, Apache License
# 2.0, available in https://github.com/CNES/patrius; see also LICENSES/PATRIUS.txt):
#
#   1. The static model is compared against anchors extracted from the density map
#      distributed with PATRIUS (resource jacchia77_tables/J77_densityMap.txt), which
#      tabulates the base-10 logarithm of the total density on a grid of exospheric
#      temperatures (200 : 25 : 3000 K) and altitudes (0 : 1 : 200 km and
#      200 : 10 : 2500 km). Our static model agrees with the map within 0.0015 in the
#      base-10 logarithm over the entire grid (the map was generated with slightly
#      different physical constants).
#
#   2. The dynamic model is compared against a line-by-line Julia port of the PATRIUS
#      class, which interpolates the density map bilinearly. The reference values below
#      were generated with that port, and the tolerance covers the bilinear interpolation
#      error of the map grid (at most 0.0013 in the base-10 logarithm over 15120
#      verification points spanning 90 km to 1500 km, all seasons, and quiet to storm
#      geomagnetic conditions). Driven by the same space indices, the port also reproduces
#      the decay time of a 500 km sun-synchronous satellite computed by STELA within
#      0.5 %.
#
############################################################################################

@testset "STELA Variant - Static Model Anchors" begin
    # Anchors (T∞ [K], z [km], log₁₀ ρ [kg / m³]) extracted from the PATRIUS density map
    # at grid nodes, avoiding any interpolation error.
    anchors = (
        (500.0, 100.0, -6.2438613),
        (500.0, 150.0, -8.8979120),
        (500.0, 300.0, -11.8248430),
        (500.0, 500.0, -14.0663220),
        (500.0, 1000.0, -15.0767110),
        (500.0, 2000.0, -15.8188010),
        (750.0, 100.0, -6.2456473),
        (750.0, 150.0, -8.7642544),
        (750.0, 300.0, -11.0559420),
        (750.0, 500.0, -13.0156560),
        (750.0, 1000.0, -14.9328970),
        (750.0, 2000.0, -15.9794780),
        (1000.0, 100.0, -6.2468457),
        (1000.0, 150.0, -8.7011871),
        (1000.0, 300.0, -10.6669090),
        (1000.0, 500.0, -12.2460600),
        (1000.0, 1000.0, -14.5475370),
        (1000.0, 2000.0, -15.7800190),
        (1500.0, 100.0, -6.2484454),
        (1500.0, 150.0, -8.6365767),
        (1500.0, 300.0, -10.2717270),
        (1500.0, 500.0, -11.4573420),
        (1500.0, 1000.0, -13.5898660),
        (1500.0, 2000.0, -15.0973290),
        (2000.0, 100.0, -6.2495306),
        (2000.0, 150.0, -8.6008757),
        (2000.0, 300.0, -10.0776640),
        (2000.0, 500.0, -11.0530620),
        (2000.0, 1000.0, -12.7853970),
        (2000.0, 2000.0, -14.6466800),
    )

    for (T∞, z, log₁₀ρ_map) in anchors
        ~, ~, ρ = AtmosphericModels._jacchia1977_static(T∞, z)
        @test log10(ρ) ≈ log₁₀ρ_map atol = 0.0015
    end
end

@testset "STELA Variant - Dynamic Model" begin
    # Reference values (ρ [kg / m³] and local exospheric temperature [K]) generated with
    # the Julia port of the PATRIUS class described in the comment above. The last case
    # exercises the geomagnetic index cap at 9.
    cases = (
        (
            DateTime("2018-06-19T18:35:00"),
            -22.0,
            -45.0,
            700e3,
            100.0,
            100.0,
            3.0,
            1.20151450e-14,
            905.9249,
        ),
        (
            DateTime("2017-03-15T06:00:00"),
            40.0,
            100.0,
            500e3,
            72.0,
            75.0,
            1.0,
            1.26109121e-13,
            760.7803,
        ),
        (
            DateTime("2023-10-01T12:00:00"),
            -60.0,
            200.0,
            350e3,
            160.0,
            150.0,
            7.0,
            2.06906347e-11,
            1319.7208,
        ),
        (
            DateTime("2020-01-05T00:00:00"),
            0.0,
            0.0,
            150e3,
            70.0,
            71.0,
            2.0,
            1.53367492e-09,
            662.8792,
        ),
        (
            DateTime("2021-12-25T21:00:00"),
            75.0,
            310.0,
            1000e3,
            110.0,
            95.0,
            12.0,
            7.42316029e-14,
            1777.6371,
        ),
    )

    for (instant, lat_d, lon_d, h, F10, F10ₐ, Kp, ρ_ref, T∞_ref) in cases
        out = AtmosphericModels.jacchia1977(
            instant, deg2rad(lat_d), deg2rad(lon_d), h, F10, F10ₐ, Kp; variant = Val(:stela)
        )

        @test out.exospheric_temperature ≈ T∞_ref atol = 0.1
        @test log10(out.total_density) ≈ log10(ρ_ref) atol = 0.004
    end

    # The variant must differ from the default SR-375 assembly.
    out_stela = AtmosphericModels.jacchia1977(
        DateTime("2018-06-19T18:35:00"),
        deg2rad(-22),
        deg2rad(-45),
        700e3,
        100.0,
        100.0,
        3.0;
        variant = Val(:stela),
    )

    out_sr375 = AtmosphericModels.jacchia1977(
        DateTime("2018-06-19T18:35:00"),
        deg2rad(-22),
        deg2rad(-45),
        700e3,
        100.0,
        100.0,
        3.0,
    )

    @test out_stela.total_density != out_sr375.total_density

    # The variant must work with reduced-precision inputs.
    out = AtmosphericModels.jacchia1977(
        2460000.25f0, 0.5f0, 0.5f0, 300.0f3, 100.0f0, 100.0f0, 3.0f0; variant = Val(:stela)
    )

    @test isfinite(out.total_density)
end

############################################################################################
#                                       Test Results                                       #
############################################################################################
#
# We select a day and run the STELA variant with and without passing the space indices.
# The result must be the same. The space indices fetched for the instant
# 2023-01-01T10:00:00.000 at 23° S, 45° W, using the 10.7-cm flux adjusted to 1 AU, are:
#
#   F10  = 159.5 sfu (value of 2022-12-31, lagged by 1.1821357920055 days)
#   F10ₐ = 151.56872332807635 sfu (Gaussian-weighted mean centered on the lagged instant,
#          as in the reference implementation)
#   Kp   = 3.0 (delayed by 0.29100570997169495 days)
#
############################################################################################

@testset "STELA Variant - Fetching All Space Indices" begin
    SpaceIndices.init()

    instant = DateTime("2023-01-01T10:00:00")
    ϕ_gd    = -23 |> deg2rad
    λ       = -45 |> deg2rad
    F10     = 159.5
    F10ₐ    = 151.56872332807635
    Kp      = 3.0

    for h in (150e3, 400e3, 1000e3)
        expected = AtmosphericModels.jacchia1977(
            instant, ϕ_gd, λ, h, F10, F10ₐ, Kp; variant = Val(:stela)
        )
        result = AtmosphericModels.jacchia1977(instant, ϕ_gd, λ, h; variant = Val(:stela))

        @test result.total_density ≈ expected.total_density
        @test result.temperature ≈ expected.temperature
        @test result.exospheric_temperature ≈ expected.exospheric_temperature
    end
end

############################################################################################
#                                       Test Results                                       #
############################################################################################
#
# The integration loops must terminate for reduced-precision inputs. Before the integer
# panel count was introduced, the termination criterion compared the accumulated altitude
# against a fixed tolerance of 1e-4 km, which is smaller than the accumulated rounding
# error of `Float32` altitudes, leading to an infinite loop.
#
############################################################################################

@testset "Reduced-Precision Inputs" begin
    # Downward hydrogen integration branch (z < 500 km).
    log₁₀_n, M̄, ρ = AtmosphericModels._jacchia1977_static(900.0f0, 150.0f0)
    @test all(isfinite, log₁₀_n)
    @test isfinite(M̄)
    @test isfinite(ρ)

    # Upward hydrogen integration branch (z > 500 km).
    log₁₀_n, M̄, ρ = AtmosphericModels._jacchia1977_static(900.0f0, 641.0f0)
    @test all(isfinite, log₁₀_n)
    @test isfinite(M̄)
    @test isfinite(ρ)

    # Public API with `Float32` inputs.
    out = AtmosphericModels.jacchia1977(
        2460000.25f0, 0.5f0, 0.5f0, 300.0f3, 100.0f0, 100.0f0, 3.0f0
    )
    @test isfinite(out.total_density)
end

@testset "Show" begin
    result = AtmosphericModels.jacchia1977(
        DateTime("2023-01-01T10:00:00"), 0, 0, 500e3, 100, 100, 3
    )

    str = sprint(show, result)
    @test startswith(str, "Jacchia 1977 output (ρ = ")

    str = sprint(show, MIME("text/plain"), result)
    @test startswith(str, "Jacchia 1977 Atmospheric Model Result:")
    @test occursin("Total density", str)
    @test occursin("H  number density", str)
end

@testset "Errors" begin
    @test_throws ArgumentError AtmosphericModels.jacchia1977(
        now(), 0, 0, 89.9e3, 100, 100, 3
    )
    @test_throws ArgumentError AtmosphericModels.jacchia1977(
        now(), 0, 0, 2000.1e3, 100, 100, 3
    )
    @test_throws ArgumentError AtmosphericModels.jacchia1977(
        now(), 0, 0, 500e3, 100, 100, 3; variant = Val(:unknown)
    )
    @test_throws ArgumentError AtmosphericModels.jacchia1977(
        now(),
        0,
        0,
        500e3,
        100,
        100,
        3;
        variant = Val(:stela),
        geomagnetic_profile = Val(:tanh),
    )
end
